site_name: Notes ASR – Neven
theme:
  name: material
  language: fr
  features: [navigation.tabs, search.suggest, content.code.copy]
  palette:
    scheme: slate
markdown_extensions:
  - admonition
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true