site_name: Notes ASR – Neven
theme:
  name: material
  language: fr
  features: [navigation.tabs, search.suggest, content.code.copy]
  palette:
    scheme: slate
markdown_extensions:
  - admonition
  - attr_list
  - md_in_html
  - tables
  - toc:
      permalink: true
  - pymdownx.details
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
